AML-21 drift detector is too sensitive
Amplo-GmbH/AutoML pull request #17
Opened 2022-04-06 20:34 UTC by tstreule

data drift is a concept where data in production differs too much from the training data (it drifted away). That’s obviously a problem for performance. We have a data drift detector that should warn for this, but it’s overly sensitive. It warns for drift even on training data.

2022-04-06 20:42 UTC, tstreule commented
Please use the following commit message for merging:

```
AML-21 drift detector is too sensitive (#17)

* Add test case for testing drift warnings

* Use custom DataDriftWarnings

* Use`warnings` module instead of `logging` (in `Amplo/AutoML/DriftDetector.py`)

* Add `DriftDetector._check_distributions` to `DriftDetector.check` (in `Amplo/AutoML/DriftDetector.py`)

* Test sensibility of DriftDetector by asserting that no `DataDriftWarning` occurred

* Bugfix `Amplo/Utils/utils.py::hist_search`
```

2022-04-07 06:24 UTC, nielsuit227 requested changes

2022-04-07 06:24 UTC, nielsuit227 commented on Amplo/AutoML/DriftDetector.py
> +                warnings.warn(DataDriftWarning("[AutoML] Output drift detected!"))
This has the potential to give a warning for every output, which is annoying when using predict on multiple samples, which is the most common usecase.

2022-04-07 06:24 UTC, nielsuit227 commented on Amplo/Utils/utils.py
> +    countdown = 1000
2 ^ 1000 = an array of length 10e+300. We'll be dealing with max 1 trillion samples, which would be 2 ^ 30, so you can make this 30.

2022-04-07 06:24 UTC, nielsuit227 commented on tests/Unit/AutoML/test_drift_detector.py
> +    return make_data(num_samples, cat_choices=False, num_dists=num_dists)
Can you put this in some test util? This is also useful for DataProcessor and FeatureProcessor :)

2022-04-07 06:57 UTC, tstreule commented on Amplo/Utils/utils.py
> +    countdown = 1000
Sure thing! 
commit 0537dbc66ff23b3b612f3ed5d2a637b2d19b281d

2022-04-07 06:57 UTC, tstreule commented on tests/Unit/AutoML/test_drift_detector.py
> +    return make_data(num_samples, cat_choices=False, num_dists=num_dists)
Sure thing!
commit 0537dbc66ff23b3b612f3ed5d2a637b2d19b281d

2022-04-07 06:57 UTC, tstreule commented on Amplo/AutoML/DriftDetector.py
> +                warnings.warn(DataDriftWarning("[AutoML] Output drift detected!"))
Good point!
commit 71deb186926423e26675db285d4db3ed1f88e870

2022-04-07 08:30 UTC, nielsuit227 approved these changes

2022-04-07 08:30 UTC, merged