AML-93 Decouple preprocessing from IntervalAnalyser (and more)
Amplo-GmbH/AutoML pull request #23
Opened 2022-04-24 21:45 UTC by tstreule

This PR addresses multiple Jira tickets at the same time, since the tickets depend on each other.

- AML-93 Decouple preprocessing from IntervalAnalyser
- AML-91 Prevent redundant data downloading
- AML-90 Prevent redundant data processing
- AML-78 Allow IntervalAnalyser with a provided dataframe instead of folder
- AML-95 Files in Metadata
- AML-96 Convert data arguments to properties

2022-04-25 05:16 UTC, tstreule commented
Whats up with codecov

2022-04-26 11:56 UTC, nielsuit227 commented on Amplo/API/interface.py
> +            Next subdirectory
Very nice with the plural yields.

2022-04-26 12:14 UTC, tstreule commented on Amplo/API/interface.py
> +            Next subdirectory
👍

2022-04-26 14:05 UTC, nielsuit227 requested changes

2022-04-26 14:05 UTC, nielsuit227 commented on tests/Integration/GridSearch/test_no_grid_search.py
> +    def tearDown(self) -> None:
the double is a bit redundant. They're not standard classmethods and execute the same code?

2022-04-26 14:11 UTC, tstreule commented on Amplo/API/storage.py
> +        )
Your desired behaviour is actually handled by the Pipeline itself

2022-04-26 14:12 UTC, tstreule commented on Amplo/API/storage.py
> +            file_last_modified: datetime = blob_properties.last_modified
For autocomplete, convenience

2022-04-26 14:13 UTC, tstreule commented on Amplo/Utils/io.py
> +    for folder in sorted(Path(path_to_folder).glob('*')):
Good point 🧐

2022-04-26 14:14 UTC, tstreule commented on tests/Integration/GridSearch/test_no_grid_search.py
> +    def tearDown(self) -> None:
Sezup guarantees that no AutoML folder exists, and teardown that the zest leaves no trace

2022-04-26 19:48 UTC, tstreule commented on Amplo/Utils/io.py
> +    for folder in sorted(Path(path_to_folder).glob('*')):
commit c41228c3bc998b338e335b2baacedf29f613398a

2022-04-26 19:48 UTC, tstreule commented on Amplo/AutoML/IntervalAnalyser.py
> +            or path to folder that is correctly structured (see Notes)
commit c41228c3bc998b338e335b2baacedf29f613398a

2022-04-26 19:48 UTC, tstreule commented on Amplo/AutoML/IntervalAnalyser.py
> +                info = '<< ? >>'  # TODO: previously it was: os.listdir(self.folder)[labels[(i, 0)]]
commit c41228c3bc998b338e335b2baacedf29f613398a

2022-04-26 19:50 UTC, tstreule commented on Amplo/Pipeline.py
> +    def conclude_fitting(self):
I tried a different approach than you proposed. 🙃
Have a look at commit c41228c3bc998b338e335b2baacedf29f613398a!

2022-04-27 06:53 UTC, tstreule commented on Amplo/Pipeline.py
> +        assert isinstance(new_x, pd.DataFrame), 'Invalid data type'
commit b63668e7784c8c6b8aeb4c6ca1740f8c226048b4

2022-04-27 06:53 UTC, tstreule commented on Amplo/Pipeline.py
> +        assert isinstance(new_y, pd.Series), 'Invalid data type'
commit b63668e7784c8c6b8aeb4c6ca1740f8c226048b4

2022-04-27 09:38 UTC, tstreule commented on Amplo/API/storage.py
> +        )
cf. `os.utime(str(local_dir / file), (file_created.timestamp(), file_last_modified.timestamp()))`

2022-04-27 11:43 UTC, tstreule commented on tests/Integration/GridSearch/test_no_grid_search.py
> +    def tearDown(self) -> None:
Okay, you won 👍 ^^

2022-05-02 07:28 UTC, nielsuit227 requested changes
Only some minor points. Did not yet check if there's regression in the tests.

2022-05-02 07:28 UTC, nielsuit227 commented on Amplo/AutoML/DataProcessor.py
> +        return settings
Minor detail; why not return this directly?

2022-05-02 07:28 UTC, nielsuit227 commented on Amplo/AutoML/DataProcessor.py
> +            self.data.loc[:, self.target] = self.encode_labels(labels, warn_unencodable=False)
What would be an example of `unencodable` labels and what happens in these cases? Maybe something to include in the tests.

2022-05-02 07:28 UTC, nielsuit227 commented on Amplo/AutoML/DataProcessor.py
> +        except NotFittedError as err:
In what case is a `NotFittedError` thrown when the `self._label_encodings` is unknown?

2022-05-02 07:32 UTC, tstreule commented on Amplo/AutoML/DataProcessor.py
> +        return settings
This adjustment is a relict from developing and has no specific reason.

2022-05-02 07:34 UTC, tstreule commented on Amplo/AutoML/DataProcessor.py
> +            self.data.loc[:, self.target] = self.encode_labels(labels, warn_unencodable=False)
With "unencodable" I mean that the labels resemble a regression task and it thus makes no sense to encode each single value to a unique class.

2022-05-02 07:37 UTC, tstreule commented on Amplo/AutoML/DataProcessor.py
> +        except NotFittedError as err:
I assume there is no other situation than that

2022-05-02 07:40 UTC, nielsuit227 commented on Amplo/AutoML/DataProcessor.py
> +        except NotFittedError as err:
Then this second clause is entirely redundant?

2022-05-02 07:46 UTC, tstreule commented on Amplo/AutoML/DataProcessor.py
> +        except NotFittedError as err:
No, I don't think so.
The `except_not_fitted` parameter is here to purposely ignore the error and return the original labels. By default it's `False` so a user realizes that it does not make sense to "decode" the labels. However, I thought it is convenient for the function `_code_target_column()` such that it can handle both, regression and classification tasks.

2022-05-02 07:48 UTC, tstreule commented on Amplo/AutoML/DataProcessor.py
> +        except NotFittedError as err:
If it makes more sense, I could change it a little bit that both, `encode_labels` and `decode_labels` raise an error if the labels resemble a regression and catch the error in `_code_target_column` instead.

2022-05-02 08:09 UTC, nielsuit227 commented on Amplo/AutoML/DataProcessor.py
> +        except NotFittedError as err:
Ah I see. You catch your own exception 🙈 . Then nvm, read the code wrong. All good :)

2022-05-02 08:09 UTC, nielsuit227 approved these changes

2022-05-02 08:09 UTC, merged