AML-37 Restrict optuna for diminishing results
Amplo-GmbH/AutoML pull request #25
Opened 2022-05-16 12:09 UTC by tstreule

This PR includes:
- Restrict optuna for diminishing results
    - Prune when cv score is bad to previous trials
    - Stop trial when...
        a. `N` trials have been pruned consecutively, and
        b. `M > N` trials have been pruned in total
- Prettify a few docstrings
- Adjust import order according to coding guidelines
- Errata in grid search testing (remove preliminary `return`)
- Adjust `merge_logs` function in utils

2022-05-16 13:00 UTC, nielsuit227 requested changes

2022-05-16 13:18 UTC, tstreule commented on Amplo/GridSearch/OptunaGridSearch.py
> +        raise NotImplementedError(f'Cannot decide whether scoring is good or bad: {scoring}')
With `neg_log_loss` I agree.

What do you mean with "we miss the goal here"? Assuming you refer to the threshold of 0.1, I think you're missing the whole picture. While `trial_is_good_enough` is one way of pruning, we also prune when a CV score has no improvements to previous trials (see variable `cv_interrupted`).

2022-05-16 13:23 UTC, nielsuit227 commented on Amplo/GridSearch/OptunaGridSearch.py
> +        raise NotImplementedError(f'Cannot decide whether scoring is good or bad: {scoring}')
`trial_is_good_enough` looks whether the score is reasonable to rely on, which is problem dependent, and trial independent. Therefore, a study without any improvements for half an hour while we still have 100s of candidates or hours left may or may not be pruned based on the difficulty of the problem. 
Instead, this should reflect on the last `x` trials, see how long there hasn't been an improvement (or even how marginal the improvements are) and decide on that whether it's useful to continue.

2022-05-16 13:37 UTC, tstreule commented on Amplo/Utils/io.py
> +    assert Path(path_to_folder).exists(), 'Directory does not exist'
Nope. See errata in commit 415085ddcca229d863ab8a8392b4b5fc8c60d683

2022-05-16 13:39 UTC, tstreule commented on Amplo/GridSearch/OptunaGridSearch.py
> +        study_stop_cb = StopWhenTrialKeepBeingPrunedCallback(15)
Good point! `IsThisABetterNameForACallback`?
see commit 6fb2b1df834b3443aecd4fbdaa447d464048139a

2022-05-17 14:51 UTC, tstreule commented on Amplo/GridSearch/OptunaGridSearch.py
> +        raise NotImplementedError(f'Cannot decide whether scoring is good or bad: {scoring}')
Do I understand you correctly that you want to compare the scores even across multiple models?

For example:
- Top 3 XGBoost models had scores: 0.8, 0.75, 0.74
- Top 3 RF models had scores: 0.79, 0.76, 0.73
Therefore, when the next model, let's say CatBoost, with the given parameter set has a score of `0.79`, then we are happy and say that the trial is good enough.

Like that?

2022-05-17 16:21 UTC, nielsuit227 commented on Amplo/GridSearch/OptunaGridSearch.py
> +        raise NotImplementedError(f'Cannot decide whether scoring is good or bad: {scoring}')
This whole ticket had one goal: Avoid running endless trials without finding improvements. 

Often found 500 trials where the optimum was trial 37. Pruning can mitigate that problem significantly. Both inside the CV but also the whole study when too many trials are crap. 

I didn't even think of using previous trials of different models on the same dataset, but that absolutely makes sense!

2022-05-18 12:12 UTC, tstreule commented on Amplo/GridSearch/OptunaGridSearch.py
> +        raise NotImplementedError(f'Cannot decide whether scoring is good or bad: {scoring}')
Please have a look at commit a2739c0d404a3ff62bbf035fb38333bbcbfb48c6

2022-05-18 12:17 UTC, nielsuit227 requested changes

2022-05-18 12:17 UTC, nielsuit227 commented on Amplo/GridSearch/OptunaGridSearch.py
> +                'Pruning with a threshold is arbitrary when the study direction is undefined.')
We still use scorers, this will always be maximize. It's not even an option in this class....

2022-05-18 12:21 UTC, tstreule commented on Amplo/GridSearch/OptunaGridSearch.py
> +                'Pruning with a threshold is arbitrary when the study direction is undefined.')
Let's get rid of it then

2022-05-18 12:22 UTC, tstreule commented on Amplo/GridSearch/OptunaGridSearch.py
> +                'Pruning with a threshold is arbitrary when the study direction is undefined.')
Let's get rid of it then

2022-05-18 12:54 UTC, merged