AML-60 Better than linear
Amplo-GmbH/AutoML pull request #28
Opened 2022-05-23 07:22 UTC by tstreule

This PR initializes the pipeline observation module to check a model whether it is ready for production.
For now only one observation is made, that is, checking whether a linear model performs better than the `best_model` found by the pipeline.

2022-05-23 07:41 UTC, nielsuit227 commented
Good stuff. Got two remarks:
- It's missing some automated testing. Would be nice to trigger this this warning, maybe we can artificially set uncorrelated features, and have the pipeline only use those. 
- Currently, you put the `_ModelObserver` hidden and in the same `observer.py` file. This is gonna get quite a big class, so don't you think it makes more sense to put it in it's own file?

2022-05-23 07:52 UTC, tstreule commented
Thanks for your feedback.

> It's missing some automated testing. Would be nice to trigger this this warning, [...]

Just to mention: Warnings _ will_ be triggered, see `base.py::BaseObserver::report_observation`. Maybe we'd prefer to trigger a warning only _once_. If so, I could check all observations in the `observer.py::ProductionObserver::observe` and trigger only one warning that summarizes all critical observations.

Concerning automated testing: I'll create a unittest that will check whether a warning will be triggered for each specific test.

> [...] maybe we can artificially set uncorrelated features, and have the pipeline only use those.

For unit testing? Because I'm not sure whether we need this "hack" to trigger a warning.

> Currently, you put the `_ModelObserver` hidden and in the same `observer.py` file. This is gonna get quite a big class, so don't you think it makes more sense to put it in it's own file?

That's a good point. I will move it to a separate file. Same thing for the `_DataObserver` that will come soon.

2022-05-23 07:56 UTC, nielsuit227 commented
> Just to mention: Warnings _ will_ be triggered, see base.py::BaseObserver::report_observation. Maybe we'd prefer to trigger a warning only once. If so, I could check all observations in the observer.py::ProductionObserver::observe and trigger only one warning that summarizes all critical observations.

Not sure if it makes such a difference whether one warning will be triggered or a sequence of warnings. Both sound fine.

> Concerning automated testing: I'll create a unittest that will check whether a warning will be triggered for each specific test.

Exactly.

> For unit testing? Because I'm not sure whether we need this "hack" to trigger a warning.

I'm not sure how else you want to trigger this warning. You need a scenario where a linear model is better than our pipeline.

2022-05-23 08:12 UTC, tstreule commented
> I'm not sure how else you want to trigger this warning. You need a scenario where a linear model is better than our pipeline.

I propose to trigger the warning when the linear model is better _or equal_. Therefore, it should be quite easy to trigger a warning for a unit test.

2022-05-24 15:02 UTC, nielsuit227 requested changes

2022-05-24 15:02 UTC, nielsuit227 commented on tests/unit/observation/test_model_observer.py
> +    x = np.concatenate([linear_col] + 20 * [noise_col], axis=1)
Now you only have one vector? The concatenate does nothing here? Just reshapes from (100, 1) to (100,)?

2022-05-24 15:02 UTC, nielsuit227 commented on tests/unit/observation/test_model_observer.py
> +            obs.check_better_than_linear()
How is this triggering the warning? Even with pure noise, the pipeline won't be always worse than a linear model?

2022-05-24 15:02 UTC, nielsuit227 commented on tests/unit/test_models.py
> +            model_params = {'CatBoostRegressor': {'depth': 10}}
This a bugfix or so?

2022-05-24 15:05 UTC, tstreule commented on Amplo/Observation/_data_observer.py
> +            series = numeric_data[col].sort_values()  # is shuffled when classification
Nope. When it's a classification task, the input data is shuffled.

2022-05-24 15:06 UTC, tstreule commented on tests/unit/observation/test_model_observer.py
> +    x = np.concatenate([linear_col] + 20 * [noise_col], axis=1)
No. `x` will end up having 1x the `linear_col` and 20x the `noise_col`, thus having 21 columns.

2022-05-24 15:08 UTC, tstreule commented on tests/unit/observation/test_model_observer.py
> +            obs.check_better_than_linear()
Heuristically, it always performed better or equal. But I'm open for discussion.

2022-05-24 15:08 UTC, nielsuit227 commented on tests/unit/observation/test_model_observer.py
> +    x = np.concatenate([linear_col] + 20 * [noise_col], axis=1)
Ah right, you wrap the arrays.

2022-05-24 15:10 UTC, nielsuit227 commented on tests/unit/observation/test_model_observer.py
> +            obs.check_better_than_linear()
Exactly, pipeline >= linear. Therefore, this warning will not be triggered in all cases. Therefore, there will be cases that this tests fails.

2022-05-24 15:11 UTC, nielsuit227 commented on Amplo/Observation/_data_observer.py
> +            series = numeric_data[col].sort_values()  # is shuffled when classification
I'm sorry, I don't get this. Where is the input data shuffled? Thinking about it, the `_data_observer` should actually be called as early as possible, before doing any steps. That way, we can identify for example id's that are still in there somehow. This test should also check within log if a multi-index is given.

2022-05-24 15:15 UTC, tstreule commented on Amplo/Observation/_data_observer.py
> +            series = numeric_data[col].sort_values()  # is shuffled when classification
That's actually a good point. We could indeed call the data observer before doing any transformations.

2022-05-24 15:20 UTC, nielsuit227 commented on tests/unit/test_models.py
> +            model_params = {'CatBoostRegressor': {'depth': 10}}
Ah no I see now. can disregard this.

2022-05-25 07:48 UTC, tstreule commented on tests/unit/observation/test_model_observer.py
> +            obs.check_better_than_linear()
New implementation see commit b7dbc95bb0de10c34d7ca60d352eb9b57f679cba. It is significantly faster in testing and a lot more stable since we're using the new `DummyPredictor` class.

2022-05-25 07:52 UTC, nielsuit227 requested changes
Nicely implemented 👍

2022-05-25 07:52 UTC, nielsuit227 commented on tests/__init__.py
> +class _DummyClassifier:
Maybe these names should imply they're random?

2022-05-25 08:30 UTC, tstreule commented on Amplo/Observation/_data_observer.py
> +            series = numeric_data[col].sort_values()  # is shuffled when classification
Decision for now: We call the data observer two times. First, directly after reading the data, and, second, after processing the data. However, for the latter case, I will add a note that it might get removed in the future.

2022-05-25 08:43 UTC, tstreule commented on tests/__init__.py
> +class _DummyClassifier:
I'll rename it to `Random[...]`

2022-05-25 08:45 UTC, tstreule commented on tests/unit/observation/test_data_observer.py
> +    yield x, y
commit 4c672f67935413ae2b73ce771fae2c1259a6a1e2

2022-05-25 08:49 UTC, nielsuit227 requested changes

2022-05-25 08:49 UTC, nielsuit227 commented on tests/unit/observation/test_data_observer.py
> +        assert monotonic_cols == [0], "Wrong monotonic columns identified."
Are we not expecting [1] here?

2022-05-25 08:53 UTC, tstreule commented on tests/unit/observation/test_data_observer.py
> +        assert monotonic_cols == [0], "Wrong monotonic columns identified."
No. As on line 8, we see that the first column (index 0) is monotonic.

2022-05-25 08:55 UTC, nielsuit227 commented on tests/unit/observation/test_data_observer.py
> +        assert monotonic_cols == [0], "Wrong monotonic columns identified."
Ah the column name in this case is 0. Thought this was the number of monotonic columns

2022-05-25 08:55 UTC, nielsuit227 submitted a review, later dismissed

2022-05-26 15:43 UTC, nielsuit227 approved these changes

2022-05-26 15:43 UTC, merged