Aml 56 minority sensitivity
Amplo-GmbH/AutoML pull request #32
Opened 2022-06-07 14:26 UTC by nielsuit227

2022-06-08 08:01 UTC, tstreule requested changes
Minor changes requested.

2022-06-08 14:44 UTC, nielsuit227 commented on Amplo/AutoML/Documenter.py
> +                                                       specificity),
106819f

2022-06-08 14:46 UTC, nielsuit227 commented on Amplo/AutoML/FeatureProcessor.py
> +                # Skip if they"re the same
38da7dc

2022-06-08 14:46 UTC, nielsuit227 commented on Amplo/AutoML/FeatureProcessor.py
> +                # Skip if they"re the same
38da7dc

2022-06-08 14:47 UTC, nielsuit227 commented on Amplo/AutoML/FeatureProcessor.py
> +                # Skip if we"re out of time
38da7dc

2022-06-08 14:51 UTC, nielsuit227 commented on Amplo/Documenting/RegressionDocumenting.py
> +        logger.info('[AutoML] Mean Absolute Percentage Error: {:.2f} \u00B1 {:.2f}'.format(
311ca40

2022-06-08 14:51 UTC, nielsuit227 commented on Amplo/AutoML/IntervalAnalyser.py
> +        Depending on the dtype of the noise attribute, the dtype of the labels" column will be affected.
311ca40

2022-06-09 07:43 UTC, tstreule requested changes

2022-06-09 07:43 UTC, tstreule commented on Amplo/Pipeline.py
> +        verbose : int, optional
Type-hinting `optional` for all these parameters is malicious. I know what you mean with "optional" (they have a default value) but by saying it's optional, you encourage users to set parameters to `None` which we do not accept.
Therefore, remove all optionals, except for `logging_level` which actually can handle `None` as input.

2022-06-09 09:07 UTC, nielsuit227 commented on Amplo/Pipeline.py
> +        verbose : int, optional
https://github.com/Amplo-GmbH/AutoML/pull/32/commits/2fa3f943f73e27c00b0d0269666db0f858de4c68

2022-06-09 13:47 UTC, nielsuit227 commented
Passing again, ready for review :)

2022-06-09 14:13 UTC, tstreule approved these changes

2022-06-09 14:31 UTC, merged